### ISSUE TITLE
How to generate "legalChildrenMap.ser"

### ISSUE THREAD

**Issue by Ringbo** [tech-srl/c3po#1]
Dear authors
Thanks for your great work!
I am very interested in your project and want to apply it to a data set written in Java. Hence I'm trying to extend this model to java, while I can't generate "legalChildrenMap.ser". It seems to be processed by other script but not included in this repo?
Could you provide the relative scripts or a guidance about how to generate a compatible file?

Thanks.
Bo.

**Comment by shakedbr** [comment]
Hi @Ringbo, 
Thank you for your interest in our work!

Please pull the latest commit.
I updated `create_dataset.sh` and added a new python script to support creating `legalChildrenMap.ser` from scratch.
Please see lines 19-24 in  `scripts/create_dataset.sh`.

In case the `legalChildrenMap.ser` is missing from the projects dir (e.g. `DataCreation/samples_50/`), the java extractor will create it only (without creating the dataset itself). Thus, we want to run the extractor on the train split projects only, and this is what lines 19-24 are doing.

Best,
Shaked

**Comment by Ringbo** [comment]
> Hi @Ringbo,
> Thank you for your interest in our work!
> 
> Please pull the latest commit.
> I updated `create_dataset.sh` and added a new python script to support creating `legalChildrenMap.ser` from scratch.
> Please see lines 19-24 in `scripts/create_dataset.sh`.
> 
> In case the `legalChildrenMap.ser` is missing from the projects dir (e.g. `DataCreation/samples_50/`), the java extractor will create it only (without creating the dataset itself). Thus, we want to run the extractor on the train split projects only, and this is what lines 19-24 are doing.
> 
> Best,
> Shaked

Ok. It works now.
It's very kind of you.
Thanks.

Best,
Bo
