### ISSUE TITLE
argv[3] should be a json file

### ISSUE THREAD

**Issue by ForeverZyh** [tech-srl/c3po#2]
https://github.com/tech-srl/c3po/blob/aa8ba95d6febffc75501cc735912570e6a076e28/scripts/create_dataset.sh#L22
https://github.com/tech-srl/c3po/blob/aa8ba95d6febffc75501cc735912570e6a076e28/DataCreation/copy_train_projects.py#L13

The script `scripts/create_dataset.sh` ran into an error when I tried to build the dataset from scratch. It seems the `argv[3]` should be a json file, so maybe instead of `${REPO_LIST}` we should fill in `${SPLITS}`?

**Comment by shakedbr** [comment]
Hi  @ForeverZyh 
Thank you for your interest in our work!

Please pull the latest commit.
I updated `create_dataset.sh` with the fix you suggested.

Best,
Shaked

**Comment by ForeverZyh** [comment]
Cool, Thanks for the prompt fix!
